module.exports = {
  AX4: {
    '.text-AX4-Large': {
      fontFamily: 'SF Pro',
      fontSize: '56px',
      fontWeight: 400,
      lineHeight: '66px',
    },
    '.text-AX4-Title1': {
      fontFamily: 'SF Pro',
      fontSize: '53px',
      fontWeight: 400,
      lineHeight: '62px',
    },
    '.text-AX4-Title2': {
      fontFamily: 'SF Pro',
      fontSize: '50px',
      fontWeight: 400,
      lineHeight: '59px',
    },
    '.text-AX4-Title3': {
      fontFamily: 'SF Pro',
      fontSize: '43px',
      fontWeight: 400,
      lineHeight: '51px',
    },
    '.text-AX4-Headline': {
      fontFamily: 'SF Pro',
      fontSize: '47px',
      fontWeight: 600,
      lineHeight: '56px',
    },
    '.text-AX4-Body': {
      fontFamily: 'SF Pro',
      fontSize: '47px',
      fontWeight: 400,
      lineHeight: '56px',
    },
    '.text-AX4-Callout': {
      fontFamily: 'SF Pro',
      fontSize: '44px',
      fontWeight: 400,
      lineHeight: '52px',
    },
    '.text-AX4-Subhead': {
      fontFamily: 'SF Pro',
      fontSize: '42px',
      fontWeight: 600,
      lineHeight: '50px',
    },
    '.text-AX4-Footnote': {
      fontFamily: 'SF Pro',
      fontSize: '38px',
      fontWeight: 400,
      lineHeight: '46px',
    },
    '.text-AX4-Caption1': {
      fontFamily: 'SF Pro',
      fontSize: '37px',
      fontWeight: 400,
      lineHeight: '44px',
    },
    '.text-AX4-Caption2': {
      fontFamily: 'SF Pro',
      fontSize: '34px',
      fontWeight: 400,
      lineHeight: '41px',
    },
  },
  AX1: {
    '.text-AX1-Large': {
      fontFamily: 'SF Pro',
      fontSize: '44px',
      fontWeight: 400,
      lineHeight: '52px',
    },
    '.text-AX1-Title1': {
      fontFamily: 'SF Pro',
      fontSize: '38px',
      fontWeight: 400,
      lineHeight: '46px',
    },
    '.text-AX1-Title2': {
      fontFamily: 'SF Pro',
      fontSize: '34px',
      fontWeight: 400,
      lineHeight: '41px',
    },
    '.text-AX1-Title3': {
      fontFamily: 'SF Pro',
      fontSize: '31px',
      fontWeight: 400,
      lineHeight: '38px',
    },
    '.text-AX1-Headline': {
      fontFamily: 'SF Pro',
      fontSize: '28px',
      fontWeight: 600,
      lineHeight: '34px',
    },
    '.text-AX1-Body': {
      fontFamily: 'SF Pro',
      fontSize: '28px',
      fontWeight: 400,
      lineHeight: '34px',
    },
    '.text-AX1-Callout': {
      fontFamily: 'SF Pro',
      fontSize: '26px',
      fontWeight: 400,
      lineHeight: '32px',
    },
    '.text-AX1-Subhead': {
      fontFamily: 'SF Pro',
      fontSize: '25px',
      fontWeight: 600,
      lineHeight: '31px',
    },
    '.text-AX1-Footnote': {
      fontFamily: 'SF Pro',
      fontSize: '23px',
      fontWeight: 400,
      lineHeight: '29px',
    },
    '.text-AX1-Caption1': {
      fontFamily: 'SF Pro',
      fontSize: '22px',
      fontWeight: 400,
      lineHeight: '28px',
    },
    '.text-AX1-Caption2': {
      fontFamily: 'SF Pro',
      fontSize: '20px',
      fontWeight: 400,
      lineHeight: '25px',
    },
  },
};
